Install peotry with --no-root
Otherwise it fails with:
```
Installing the current project: java-driver (3.7.1)

Error: The current project could not be installed: No file/folder found for package java-driver
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
If you did intend to install the current project, you may need to set `packages` in your pyproject.toml file.
```